spring.application.name=proyecto

# Server Port
server.port=8080

# PostgreSQL datasource (Supabase)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.zdobhnxhtrrcxcknlvem.supabase.co:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Callupe003187.}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Las semillas de datos se cargan desde DataInitializer.java
# OAuth2 - Google Login
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:id-vacio}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:secreto-vacio}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}



